name: inflation-calculator # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple inflation calculator app, written in Flutter. # 79 char long summary
description: |
  The money supply is increasing at a historic rate. 
  We are all becoming poorer as a result. 
  Use this tool to visualise the impact of inflation on your purchasing power.
  Built in Flutter with data from statbureau.org

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  inflation-calculator:
    plugin: flutter
    source: https://github.com/local-optimum/inflation_calculator.git
    flutter-target: lib/main.dart

apps:
  inflation-calculator:
    command: inflation_calculator
    extensions: [flutter-master]
    dbus-inflation-calculator: # adjust accordingly to your app name
      interface: dbus
      bus: session
      name: dev.site.super_cool_app 