name: inflation-calculator # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple inflation calculator app, written in Flutter. # 79 char long summary
description: |
 Cash is not a store a value.
 Model the declining value of your money over time using this simple app.
 Created by Local Optimum using data from statbureau.org

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  inflation-calculator:
    plugin: flutter
    source: https://github.com/local-optimum/inflation_calculator.git
    flutter-target: lib/main.dart

apps:
  inflation-calculator:
    command: inflation_calculator
    extensions: [flutter-master]
    plugs:
      [network]

